//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Data.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add null entity into {0} repository.
        /// </summary>
        internal static string CannotAddNullEntity {
            get {
                return ResourceManager.GetString("CannotAddNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify null item into {0} repository.
        /// </summary>
        internal static string CannotModifyNullEntity {
            get {
                return ResourceManager.GetString("CannotModifyNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove null entity into {0} repository.
        /// </summary>
        internal static string CannotRemoveNullEntity {
            get {
                return ResourceManager.GetString("CannotRemoveNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot track null item into {0} repository.
        /// </summary>
        internal static string CannotTrackNullEntity {
            get {
                return ResourceManager.GetString("CannotTrackNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter expression cannot be null.
        /// </summary>
        internal static string FilterCannotBeNullException {
            get {
                return ResourceManager.GetString("FilterCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes expression cannot be null.
        /// </summary>
        internal static string IncludesCannotBeNullException {
            get {
                return ResourceManager.GetString("IncludesCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageCount must be positive value.
        /// </summary>
        internal static string InvalidPageCountException {
            get {
                return ResourceManager.GetString("InvalidPageCountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex must be positive value.
        /// </summary>
        internal static string InvalidPageIndexException {
            get {
                return ResourceManager.GetString("InvalidPageIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderBy expression cannot be null.
        /// </summary>
        internal static string OrderByExpressionCannotBeNullException {
            get {
                return ResourceManager.GetString("OrderByExpressionCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification cannot be null.
        /// </summary>
        internal static string SpecificationIsNullException {
            get {
                return ResourceManager.GetString("SpecificationIsNullException", resourceCulture);
            }
        }
    }
}
